### PR TITLE
Backoff strategy can be disabled and doc improvements

### PR DESCRIPTION
**Pull request by ingorichtsmeier**
Adjusted the docs to clarify the Long Polling control and the backoff strategy.

Sorry for adding old pull request again, but im not the master on GIT.

related to CAM-9280

### CODE REVIEW

**Comment by tasso94** [comment]
Hey Ingo,

thank you for your contribution.
What is the use case for `NoBackoffStrategy`?

Cheers
Tassilo

**Comment by ingorichtsmeier** [comment]
I've seen, that backoff is used, when you activate Long Polling and no requests come in.

The rest client starts waiting, per default up to a minute. But with Long Polling you would expect an immediate answer.

The `NoBackoffStrategy`is the most easy way to get this.

Activate it with `ExternalClient.create().backoffStrategy(new NoBackoffStrategy()).build()`.

Maybe we should add this option together with all other configuartions to the README as well.

**Comment by tasso94** [comment]
Hi Ingo,

this is expected behavior as the client-side backoff is only applied in case of no tasks are returned.

Cheers,
Tassilo

**Comment by ingorichtsmeier** [comment]
But the ExponentialBackoffStrategy is set as default. 

If I want an immediate new request after the long running is over, I have to disable ExponentialBackoff.

This can be done most easy with NoBackoffStrategy.

**Comment by tasso94** [comment]
Hi Ingo,

we discussed your use case internally and came up with a slightly different solution. On bootstrapping the client it is now possible to disable the backoff strategy entirely by calling `#disableBackoffStrategy`. Additionally, I slightly adjusted your documentation changes and merged them to master.

Cheers,
Tassilo

**Comment by ingorichtsmeier** [comment]
Ok, makes sense.

Could you please release the changes as a new version as soon as possible?

**Comment by tasso94** [comment]
Hey Ingo,

unfortunately this is not possible. The release cycle of the client is bound to the Camunda BPM Platform. However, in the meantime you could configure the `ExponentialBackoffStrategy` with maxTime 0.

Cheers,
Tassilo

**Pull request closed without merging**
