### PR TITLE
CAM-10670 - #29: introduction of builder pattern for RequestExecutor

### PR DESCRIPTION
**Pull request by rfelgent**
Here my contribution for #29 .

I am unsure how to handle `EngineClientLogger`

### CODE REVIEW

**Comment by marstamm** [comment]
Hi @rfelgent ,

Thank you for your Contribution. I created the Ticket for it and will forward it to be reviewed. You can track the progress here:

https://app.camunda.com/jira/browse/CAM-10670

**Comment by rfelgent** [comment]
Hi @marstamm ,

thank you for your assistance.

Pls be reminded, that the PR is not finished yet. I pushed a first version of it ony, as I need support by @tasso94 - the original creator of the code. But I think the PR shows very well what my intentions of the refactoring.
 
Following points should be disscuessed:

- handling of `EngineClientLogger` (in regards to its method visibility and wiring with Apache Http Stuff)
- where is the best place to create the ObjectMapper ? I suggest to move it from `ExternalTaskClientBuilder` to the new `RequestExecutorBuilder`
- how to handle the dataformat: You need this information at two places: ObjectMapper and TypedValues 

Best regards

**Comment by ThorbenLindhauer** [comment]
Hi @rfelgent,

As @tasso94 is currently busy with other things, @mboskamp will handle this PR and answer your questions.

Cheers,
Thorben

**Comment by mboskamp** [comment]
Hi @rfelgent 

I just looked into your changes. I have one hint: We should avoid mixing impl and non-impl interfaces. When an interface is non-impl it is considered public API and is guaranteed to be backward compatible in future versions. Here, I think it makes sense to make all of this public API to make it more accessible for others. So RequestExecutorBuilder and RequestExecutor should not be in an org.camunda.cam.bpm.client.impl package.

Regarding your questions:

The logging should remain the same for the default implementation. Any new implementations can use the same EngineClientLogger or implement logging themselves. What is your current concern with the EngineClientLogger?

Moving the ObjectMapper into the new RequestExecutorBuilder seems fine. We should clarify in the javadocs what method calls are mandatory.

By "handling the dataformat" do you mean the dateFormat that is used by the ObjectMapper and DateValueMapper? If we move the creation of the objectMapper to the RequestExecutorBuilder, I suggest we pass the dateFormat from the ExternalTaskClientBuilder and still use it there for the typedValues.

I am happy to discuss this with you.
Cheers,
Miklas

**Comment by rfelgent** [comment]
HI @mboskamp ,

sorry for my late respone.
Are there any other channels (slack, skype even telephone (I am located in Berlin)) to clarify things?!

Cheers,
Rene

**Comment by mboskamp** [comment]
Hi @rfelgent,

I am very happy to discuss your questions here on GitHub or in our [forum](https://forum.camunda.org/). Unfortunately, we can not offer any other channels.
Thank you for your understanding.

Cheers,
Miklas

**Comment by rfelgent** [comment]
Hi @mboskamp ,

> I just looked into your changes. I have one hint: We should avoid mixing impl and non-impl interfaces. When an interface is non-impl it is considered public API and is guaranteed to be backward compatible in future versions. Here, I think it makes sense to make all of this public API to make it more accessible for others. So RequestExecutorBuilder and RequestExecutor should not be in an org.camunda.cam.bpm.client.impl package.

Pls give me a hint where to place the new classes; the interfaces like `RequestExecutorBuilder` and `RequestExecutor` as well as `HttpComponentsRequestExecutor`

> The logging should remain the same for the default implementation. Any new implementations can use the same EngineClientLogger or implement logging themselves. What is your current concern with the EngineClientLogger?

Primarily, the `EngineClientLogger` is specifically made for http-components which reduces the re-usabality for other http engines (the builder pattern for `RequestExecutor` allows the usage of other http engines)
  
Secondly, the visibility of all methods within `EngineClientLogger` are protected. Depending on where we put implementations of `RequestExecutor` (at the time of writing only `HttpComponentsRequestExecutor` is available) we are forced to change that. This touches partly your first sentence of your previous comment

> Moving the ObjectMapper into the new RequestExecutorBuilder seems fine. We should clarify in the javadocs what method calls are mandatory.

Ok, I will make changes to my PR.

> By "handling the dataformat" do you mean the dateFormat that is used by the ObjectMapper and DateValueMapper? If we move the creation of the objectMapper to the RequestExecutorBuilder, I suggest we pass the dateFormat from the ExternalTaskClientBuilder and still use it there for the typedValues.

Ok, I will make changes to my PR.

Cheers, 
René

**Comment by rfelgent** [comment]
Hi @mboskamp ,

I made some changes.

In my opinion we should make the logic of `RequestInterceptorHandler` a part of `HttpComponentsRequestExecutor` as it is dependent on http-components. We can keep the "interceptor" idea as an api/facade over specific implementations of `RequestExecutor`. 
What do you think?

**Comment by mboskamp** [comment]
Hi @rfelgent,

thanks for the update. We are currently very busy but I will look into this during the next days and come back to you by the end of the week.

Cheers,
Miklas

**Comment by mboskamp** [comment]
Hi @rfelgent,

after discussing this internally, we decided that there is maybe a better solution for making the RequestExecutor configurable. 

By using the Service Loader Pattern we could provide the default implementation of the RequestExecutor without needing a builder. We would also not need to adjust the ExternalTaskClientBuilder. We wouldn't even change the public API.

Have a look at the [org.camunda.bpm.client.spi](https://github.com/camunda/camunda-external-task-client-java/tree/master/client/src/main/java/org/camunda/bpm/client/spi) package. The default implementations for the included interfaces are set through [src/main/resources/META-INF/services/org.camunda.bpm.client.spi.DataFormatProvider](https://github.com/camunda/camunda-external-task-client-java/blob/master/client/src/main/resources/META-INF/services/org.camunda.bpm.client.spi.DataFormatProvider) and loaded dynamically. (e.g. [here](https://github.com/camunda/camunda-external-task-client-java/blob/master/client/src/main/java/org/camunda/bpm/client/impl/ExternalTaskClientBuilderImpl.java#L284-L292))

I suggest building something similar for the RequestExecutor. I think that this is a) more consistent with what we already provide for Dataformat, b) does not introduce a lot of complexity and c) it does not require additional public API. Let me know if this works out for you. 

Regarding logging: Every implementation of the RequestExecutor should handle logging on its own (i.e. by implementing its own logger extending ExternalTaskClientLogger).

Cheers,
Miklas

**Comment by rfelgent** [comment]
Hi @mboskamp 

> 
> after discussing this internally, we decided that there is maybe a better solution for making the RequestExecutor configurable.
> 
> By using the Service Loader Pattern we could provide the default implementation of the RequestExecutor without needing a builder. We would also not need to adjust the ExternalTaskClientBuilder. We wouldn't even change the public API.
> 
> Have a look at the [org.camunda.bpm.client.spi](https://github.com/camunda/camunda-external-task-client-java/tree/master/client/src/main/java/org/camunda/bpm/client/spi) package. The default implementations for the included interfaces are set through [src/main/resources/META-INF/services/org.camunda.bpm.client.spi.DataFormatProvider](https://github.com/camunda/camunda-external-task-client-java/blob/master/client/src/main/resources/META-INF/services/org.camunda.bpm.client.spi.DataFormatProvider) and loaded dynamically. (e.g. [here](https://github.com/camunda/camunda-external-task-client-java/blob/master/client/src/main/java/org/camunda/bpm/client/impl/ExternalTaskClientBuilderImpl.java#L284-L292))
> 
> I suggest building something similar for the RequestExecutor. I think that this is a) more consistent with what we already provide for Dataformat, b) does not introduce a lot of complexity and c) it does not require additional public API. Let me know if this works out for you.

a) I understand your motivations. On the other hand, I have my doubts the way the ServiceLocator is used (internally) in conjunction with the (public) builder pattern. There are 2 places to configure ExternalTaskClients - it _feels_ strange to me.
b) this was the bad feedling since the beginning of my PR... a lot of changes by "unnecessary" complexity (But I did not know better at the time of writing...)
c) agreed.

I think, it is time to "rollback" my ideas and changes. 
My goal was and is to find a comfortable way to configre the http engine: currently Apache HttpClient. The introduction of the buildern pattern for the `RequestExecutor` achieves that goal but leads too other complexity which can be regarded as "overhead" in relation to _my_  primary goal.

So what do you think of `Configurators` or `Customizers` ? Something like this:

`
public interface Customizer {
      public HttpClientBuilder configure(HttpClientBuilder builder) {
         // either manipulate the given instance or create a complete new instance....
        return builder;
      }
}
`
Technically, we could introduce basic Generic<T> interface allowing to customize `HttpClientBuilder` or `ObjecMapper` (if desired some day)  or class `XXX`.

What do you think?

Cheers,
Rene

**Comment by rfelgent** [comment]
ping

**Comment by yanavasileva** [comment]
Hello Rene,

Sorry about the delay.
We will try to get back to you next week, I hope you are fine with that.

Best regards,
Yana

**Comment by mboskamp** [comment]
Hi @rfelgent,

sorry for the late response. 
Regarding your Customizer/Configurator approach, just to make sure we are on the same page:
We would have something like the following in ExternalTaskClientBuilder

```HttpClientBuilder customizeHttpClient(HttpClientBuilder builder);```

and call this in RequestExecutor#initHttpClient after the httpClientBuilder has been initialized.

I think this would be a nice approach to this. You would be able to customize the httpClient fully, and we would not have to fiddle around with ObjectMapper.

Cheers,
Miklas

**Comment by mboskamp** [comment]
Hi @rfelgent,
any news on this?

Cheers,
Miklas

**Comment by rfelgent** [comment]
Hi @mboskamp,

imho I would add a method like 

`
  addCustomizer(XXX customizer)
`

to the `ExternalTaskClientBuilder`

As I wrote earlier, the concrete design of the customizer interface (Generics, TypedInterfaces and so on) must be discussed.

The customizer for the HttpClientBuilder instance is then used in the RequestExecutor#initHttpClient.

**Comment by mboskamp** [comment]
Hi @rfelgent,
sounds good to me :)
Feel free to hack away and commit some code!

Cheers,
Miklas

**Comment by mboskamp** [comment]
Hi @rfelgent,

we haven't heard from you for some time. I will close this PR for now. Feel free to re-open it if you want to push the discussed implementation.

Cheers,
Miklas

**Pull request closed without merging**
