### PR TITLE
use executor #1

### PR DESCRIPTION
**Pull request by osteinhauer**

### CODE REVIEW

**Comment by tasso94** [comment]
Hey Oliver,

thank you for your contribution!

I will look into it and provide you some review hints later this week.

Cheers,
Tassilo

**Comment by tasso94** [comment]
Hi Oliver,

thanks a lot for your patience. As promised, here are some ideas to improve your approach.

At the moment the `Executor` takes care of fetching for new tasks as well as executing the handler. I think the fetching part should be handled internally by a single thread.

And here is why:
* a huge amount of active subscriptions (200+) lead to multiple, concurrent and recurring fetch requests. This is a bottle neck as the connection pool of the application server will be exhausted at one point. In this case, further requests are rejected. 
* the REST API endpoint (`/external-task/fetchAndLock`) is designed to fetch tasks for multiple topics at once with a single request – this is very economical in terms of resources

My proposal is to create a new class `ExternalTaskHandlerRunnable` which implements the `Runnable` interface. The logic which [executes the task handler](https://github.com/camunda/camunda-external-task-client-java/blob/master/client/src/main/java/org/camunda/bpm/client/topic/impl/TopicSubscriptionManager.java#L117-L123) should be moved to `ExternalTaskHandlerRunnable#run` and be replaced with `Executor#execute(new ExternalTaskHandlerRunnable(taskHandler, externalTask, service))`. This allows that the execution of handlers can be scaled via the `Executor` by the user.

Let me know what you are thinking about this. 🙂

Cheers,
Tassilo

**Comment by tasso94** [comment]
Hey Oliver,

I am glad that you agree with my proposal. As soon as the changes are applied accordingly, I will merge your pull request. 

Please let me know if you need any further assistance.

Cheers,
Tassilo

**Comment by osteinhauer** [comment]
Hey Tassilo.

Decided to use Callable instead of Runnable interface to have a blocking invocation of task handlers. That's the same behavior no matter how many threads are used.

Cheers,

Oliver

**Comment by tasso94** [comment]
Hey Oliver,

thank you for your contribution. 

This week I'm unfortunately not able to look into your latest changes.
I will give you a follow-up as soon as possible.

Stay tuned!

Cheers,
Tassilo

**Comment by tasso94** [comment]
Hey Oliver,

just to give you a brief heads up. This week we are busy with preparing the alpha release of Camunda BPM Platform. This means that I have to postpone to look into your pull request to next week.

Sorry for that!

Cheers,
Tassilo

**Comment by tasso94** [comment]
Hey Oliver,

please feel free to open this pull-request again if you want to tackle this feature.

Cheers,
Tassilo

**Pull request closed without merging**
